### ISSUE TITLE
JailbreakDetect ловит симулятор

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/iOS-Utils#11]
JailbreakDetect говорит, что у симулятора `isJailBroken() == true`.
Мне кажется, что это баг, потому как очевидно, что Simulator не может быть с Jailbreak.

Воспроизводится на:
Xcode 9.4.1
Simulator iPhone X/iPhone SE with iOS 11.4

**Comment by fixique** [comment]
Не знаю как тут пр прикрепить, поэтому просто отпишу тут. https://github.com/surfstudio/iOS-Utils/pull/13
