### ISSUE TITLE
Поднять версию swift

### ISSUE THREAD

**Issue by chausovSurfStudio** [surfstudio/iOS-Utils#20]
У нас в podspec
```Swift
  s.ios.deployment_target = '10.0'
  s.swift_version = '4.1'
```
Почему бы до 4.2 не поднять?

И кстати по поводу deployment_target == 10 - в самом проекте
![2019-01-02 16 50 29](https://user-images.githubusercontent.com/8776643/50594666-8af63380-0eae-11e9-8f3e-09d4b57255c9.png)
тоже может быть изменить?

**Comment by ismetanin** [comment]
@chausovSurfStudio А у нас все смигрировали уже на 4.2? 
Deployment target думаю надо понизить в проекте

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fixique** [comment]
Зенит не мигрировал на новый свифт(

**Comment by fixique** [comment]
Кое что не мигрировало на новый свифт

**Comment by LastSprint** [comment]
#31
