### ISSUE TITLE
JailBreakDetector

### ISSUE THREAD

**Issue by LastSprint** [surfstudio/iOS-Utils#35]
<img width="1200" alt="Снимок экрана 2019-05-31 в 20 29 37" src="https://user-images.githubusercontent.com/22478978/58723518-efc4a400-83e2-11e9-89c7-19d0682a7a88.png">

I think we should rename this class and method...

**Comment by fixique** [comment]
Из-за того, что реверсится название метода?    
Есть варианты по названиям? Это что-то неявное должно быть :thinking_face:
