### ISSUE TITLE
LayoutHelper iPad support

### ISSUE THREAD

**Issue by JohnReeze** [surfstudio/iOS-Utils#56]
Сейчас я вижу, что есть iphone поддержка только маленького, обычного и X+ поколений. Может быть можно добавить еще для верстки под iPad опции какие-то?

**Comment by chausovSurfStudio** [comment]
поправлено в рамках https://github.com/surfstudio/iOS-Utils/pull/89
ожидаемая версия с выпущенной правкой - 12.1.0
