### ISSUE TITLE
Заменить pod/spm Device на отдельную локальную утилиту или найти аналог

### ISSUE THREAD

**Issue by Alelenka** [surfstudio/iOS-Utils#79]
Сейчас [Device](https://github.com/Ekhoo/Device) давно забыт и не поддерживается, а нам нужно периодически обновлять устройства и вносиьт правки и расширения
При этом spm сейчас смотрит на форк этой библиотеки с поддержкой spm

**Comment by chausovSurfStudio** [comment]
поправлено в рамках https://github.com/surfstudio/iOS-Utils/pull/88
будет выпущено в версии 12.1.0
